name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.17.0
          run_install: true

      - name: Install dependencies
        run: pnpm install

      - name: cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - run: pnpm run build
      - run: pnpm run update
      - run: pnpm run gen
        working-directory: ./packages/site

      - run: pnpm run test
        env:
          CI: true

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
